<!DOCTYPE html>
<html>
<head>
    <title>PHP in HTML</title>
    <meta charset="UTF-8">
</head>
<body>
    <h1>Welcome to PHP</h1>
    
    <?php
        // کد PHP داخل HTML
        echo "<p>This is generated by PHP!</p>";
        echo "<p>Current date: " . date('Y-m-d') . "</p>";
    ?>
    
    <p>This is static HTML.</p>
</body>
</html>
